name: Build Zeek on Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Install dependencies
        run: |
          choco install -y --no-progress conan --version=1.58.0
          choco install -y --no-progress winflexbison3

      - name: Checkout Zeek
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Build Zeek
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          mkdir build
          cd build
          cmake.exe .. -DCMAKE_BUILD_TYPE=release -DENABLE_ZEEK_UNIT_TESTS=yes -G Ninja
          cmake.exe --build .
          cmake.exe --install .
        shell: cmd
